[ClassVersion("1.0.0")]
Class MSFT_xSQLServerDatabaseFile
{
    [write]String Name;
    [write]String Type;
    [write]String Path;
    [write]String Size; //FIXME: set correct data types
    [write]String MaxSize;
    [write]String Growth;
    [write]String GrowthType;
};

[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerDatabase")]
class MSFT_xSQLServerDatabase : OMI_BaseResource
{
    [Key, Description("The name of the Database.")] String Name;
    [Write, Description("If the values should be present or absent. Valid values are 'Present' or 'Absent'. Default Value is 'Present'."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("If the database should be contained. Valid values are 'None' or 'Partial'."), ValueMap{"None","Partial"}, Values{"None","Partial"}] String Containment;
    [Write, Description("List of objects with the properties Name, Type, Path, Size, MaxSize, Growth and GrowthType."), EmbeddedInstance("MSFT_xSQLServerDatabaseFile")] String Files[];
    [Key, Description("The SQL Server for the database.")] String SQLServer;
    [Key, Description("The SQL instance for the database.")] String SQLInstanceName;
};
